### ISSUE TITLE
UTC?

### ISSUE THREAD

**Issue by jstayton** [vvo/tzdb#21]
Hey @vvo 👋 

There's probably a good reason why, but I'm curious: Why is UTC not in the list?

I'm building an app with more of a developer focus, and I suspect some will want that option to align dates/times with their other tools that use UTC.

Thanks for building this!

**Comment by vvo** [comment]
Hi there @jstayton, there's no good reason as for why UTC is not in the list indeed. The thing is, UTC is not a time zone per the IANA list, it's a standard (I am no expert, I just googled it because it seemed weird :D https://www.timeanddate.com/time/aboututc.html).

But I think it could be a good idea to have an option in getTimeZones() to include UTC programmatically to the list.

If you feel like contributing to the library, this can be a good first contribution! Something like: getTimeZones({includeUtc: true}); that would then include the UTC value at the right position in the list.

**Comment by jstayton** [comment]
> UTC is not a time zone per the IANA list, it's a standard

Ah, I guess that makes sense. It's interesting that you can specify it as a time zone in most code though (like Luxon).

Anyway, I will send a PR your way if/when I get to the point of needing it. Thanks!

**Comment by vvo** [comment]
For the record: I think it's a good idea to include UTC and I will need it too in my application, so happy to see a contribution if you feel like it!

The way you could implement it:

Before sorting timezones in getTimeZones, right after the map (here: https://github.com/vvo/tzdb/blob/d38b282bc3896bc20c9a5ea04452a181911fef5c/lib/getTimeZones.js#L28) you could inject a new timezone for UTC. Its name should be "utc" (or anything DateTime.fromObject would understand as utc. Then putting the right values for its attributes:

```js
{
  name: 'America/Dawson_Creek',
  alternativeName: 'Mountain Time',
  group: [ 'America/Creston', 'America/Dawson_Creek', 'America/Fort_Nelson' ],
  countryName: 'Canada',
  mainCities: [ 'Fort St. John', 'Creston' ],
  rawOffsetInMinutes: -420,
  rawFormat: '-07:00 Mountain Time - Fort St. John, Creston',
  currentTimeOffsetInMinutes: -420,
  currentTimeFormat: '-07:00 Mountain Time - Fort St. John, Creston'
}
```

(Example)

And see how it goes!

**Comment by vvo** [comment]
(reopening this as I believe it must be done, by you or me!)

**Comment by vvo** [comment]
@jstayton I am following up on this, but I am not sure what key/values should represent the UTC time zone. Can you help? What would you like to have as a time zone object representing the UTC time zone. For example, there would be no cities associated since it's not tied to any particular region.

Let me know!

**Comment by jstayton** [comment]
What do you think about this?

```js
{
  name: "UTC",
  alternativeName: "Coordinated Universal Time (UTC)",
  abbreviation: "UTC",
  group: [ "UTC" ],
  countryName: null,
  continentCode: null,
  continentName: null,
  mainCities: [ ], // ...or `null`?
  rawOffsetInMinutes: 0,
  rawFormat: "+00:00 Coordinated Universal Time (UTC)",
  currentTimeOffsetInMinutes: 0,
  currentTimeFormat: "+00:00 Coordinated Universal Time (UTC)"
}
```

**Comment by spersico** [comment]
I agree that this might be useful, although I've got 2 suggestions:
- I've read in a couple of places that UTC is "not really a time zone". This might mean that having this as a choice might have implications for some apps (I can imagine, for example, some library that doesn't support having "UTC" as a time zone to save/parse/show). So I propose that this could be behind a flag or a prop to the function call.
- I believe that **countryName**, **continentCode** and **continentName** should be empty strings, and **mainCities** should have a single empty string value. This is to avoid a difference data type (for every codebase that simply makes a comparison of strings, such as:
`const tz = timezones.find(element=> element.mainCities[0].localeCompare(inputValue))`
Would throw an error, if no empty string as a city gets introduced (if this sounds dirty, then another approach would be having this behind a major update... just pointing out that this could be a breaking change for a lot of folks).

**Comment by athrunsun** [comment]
@vvo The `includeUtc` option should be mentioned in the documentation, took me sometime to find out this lib already supports UTC timezone.

**Comment by vvo** [comment]
@athrunsun feel free to upgrade the README directly then that would be very useful for others indeed.
