### ISSUE TITLE
Fix Abbreviations

### ISSUE THREAD

**Issue by webserveis** [vvo/tzdb#247]
Not found `KST` in abbreviations  reference "Korea Standard Time"

Check other abbreviations https://raw.githubusercontent.com/dmfilipenko/timezones.json/master/timezones.json
and
https://www.timeanddate.com/time/zones/

**Comment by vvo** [comment]
@webserveis feel free to open a PR 👍

**Comment by vvo** [comment]
I believe this was fixed? Let me know in the latest version
