### ISSUE TITLE
Support for getting only abbreviations

### ISSUE THREAD

**Issue by suryarajendhran** [vvo/tzdb#248]
It would be cool if we could do something like tzdb.getAbbreviations() to get all of the abbreviations from tzdb. Happy to raise a PR if you're open to this.

**Comment by vvo** [comment]
@suryarajendhran I think we could publish the abbreviations.json inside the npm package directly (just add to add the file to the package.json files attribute).

And then add some documentation about that.

Send a PR! :)

**Comment by suryarajendhran** [comment]
@vvo PR up! :)
