### ISSUE TITLE
Add support for acronyms

### ISSUE THREAD

**Issue by vvo** [vvo/tzdb#26]
Provide PST acronyms in data object

**Comment by ImanMahmoudinasab** [comment]
Any plan for this feature?

**Comment by vvo** [comment]
Data now contains an `abbreviation` field for each time zone. This is a manual list, some abbreviations may be inexact/incorrect/missing. Let me know in a new issue when that's the case.

**Comment by ImanMahmoudinasab** [comment]
Glad to hear that.

> Let me know in a new issue when that's the case.

Sure!
