### ISSUE TITLE
How to know when apply Daylight Time Savings?

### ISSUE THREAD

**Issue by fsc7** [vvo/tzdb#64]
Hello, I have one question. How can I know when to apply the Daylight time savings?

**Comment by vvo** [comment]
@fsc7 To know that, you should use luxon: https://moment.github.io/luxon/docs/manual/tour.html which will automatically apply DST and also let you know if DST is active when creating a date for a zone at a specific time

tzdb does not contains the exact dates of when to apply DST changes. But luxon will use what your system knows (Node.js includes IANA database, which contains when DST changes).

Let me know if this works for you.

**Comment by fsc7** [comment]
@vvo thanks for the prompt response. I will give it a try.
