### ISSUE TITLE
Add a scoring factor(like population) to limit the number of time zones

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [vvo/tzdb#75]
**Problem:**
The problem is, the number of time zones is a lot, and showing all of them at once is neither user-friendly nor performant.

**Solutions:**
A solution to this in most cases can be showing a limited number of time zones when a user opens the menu. Then they can search for more items (time zones).

**Implementation**
Ideally, there should be a `score` value in each time zone, that should be based on some dynamic/static criteria like users' time zone, offset/distance from a specific time zone/country, the popularity of the time zones, etc.
An easier implementation can be including the population of the biggest cities of a time zone so that developers can filter and show the most populated ones. I would like to see the population of the biggest city for each time zone as a quick solution.

**Comment by vvo** [comment]
> The problem is, the number of time zones is a lot, and showing all of them at once is neither user-friendly nor performant.
You're totally right. You should not just show a list of all timezones, but rather show a list of timezones including a search field.

But doing so is outside of the scope of this library. In fact, I built the library the way it is so I could build exactly what you're talking about: a timezone selector with a search field, where you can search for cities.

I would not advise anyone to limit the number of time zones, as the current number of time zones is the smallest I could go down without ignoring important time zones.

I modeled the list of time zones on the Google calendar time zones selector:

![image](https://user-images.githubusercontent.com/123822/94660482-0005cf80-0306-11eb-9872-a5e93d24b4af.png)

But even the google way of showing the time zone selector is not perfect, they went the "safe" way by not showing cities names etc.

If you want to use tzdb to build a good timezone selector, you could use:
- https://github.com/tbleckert/react-select-search
- https://react.semantic-ui.com/modules/dropdown/
- https://react-select.com/
- https://www.downshift-js.com/

Here's what I built:
![Kapture 2020-09-30 at 10 14 58](https://user-images.githubusercontent.com/123822/94660551-16ac2680-0306-11eb-9143-a885d10fd63a.gif)

I try to build libraries that are generic enough to allow any use case. For example, you can definitely preselect the timezone of the user, like this: `Intl.DateTimeFormat().resolvedOptions().timeZone` (this gets the user timeZone).

Good luck!
