### ISSUE TITLE
typescript abbreviation missing

### ISSUE THREAD

**Issue by ofbeaton** [vvo/tzdb#77]
The typescript definitions file seems to be missing the `abbreviation` attribute.

https://github.com/vvo/tzdb/blob/master/index.d.ts

Not sure if it is missing any others.

**Comment by justindra** [comment]
Adding one more Typescript issue. When importing just the names, it seems like you have just exported it out as a type.

![image](https://user-images.githubusercontent.com/4289486/97049108-fb60bf80-152f-11eb-9035-5015da3123b6.png)

Code used:

```ts
import { timeZonesNames } from '@vvo/tzdb';

const test = timeZonesNames.includes('America/Los_Angeles');
```

**Comment by vvo** [comment]
This was fixed I believe
