### ISSUE TITLE
use peerDependency

### ISSUE THREAD

**Issue by ofbeaton** [vvo/tzdb#79]
I suggest that you convert the `luxon` dependency to a peerDependency in the package.json
Not only will this underscore that luxon is in use to users of the package, but give them more freedom to version it.

Myself, I was surprised that it was being imported, since I was already using another library `date-fns-tz` since it supports tree-shaking and `luxon` does not. But if I continue to use this package, I would likely convert to `luxon` since it will be included either way and it seems silly to include 2 time libraries.

It would also be good to mention it in the readme as many people are considered about bundle size when dealing with time libraries, especially when converting from moment.

Thanks for this package though, it's working great and was exactly what I was looking for!

**Comment by ofbeaton** [comment]
Bonus points if a time library could be removed completely without significantly increasing bundle size.

**Comment by boan-anbo** [comment]
Seconded. I was surprised that Luxon became the largest module @69kb in my whole SPA bundle.

**Comment by vvo** [comment]
Hey @boan-anbo and @ofbeaton this is definitely a valid idea. Right now tzdb depends on luxon directly, it's not just a devDependency.

BUT, one could update https://github.com/vvo/tzdb/blob/master/lib/formatTimeZone.js and https://github.com/vvo/tzdb/blob/master/lib/getTimeZones.js to not use luxon I believe. We use it very lightly and the browser APIs like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat may be sufficient.

If you're really concerned about bundle size (which is a good thing!) then give it a try and open a PR. Thanks

**Comment by vvo** [comment]
Hey there, luxon was removed from dependencies, thanks!
