### ISSUE TITLE
Remove sort-on dependency?

### ISSUE THREAD

**Issue by n-po** [vvo/tzdb#85]
It would be nice to remove or replace the sort-on dependency. In angular 10 production builds this warning appears:
```
node_modules/@vvo/tzdb/lib/getTimeZones.js depends on 'sort-on'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

```

**Comment by vvo** [comment]
@n-po Right now most of npm I guess is a mix of common js and ES modules. There's little chance this will be solved ever. That would mean having every module in npm as an ES module.

Instead, I guess what you can do is configure this particular module as shown in the angular documentation you linked.

That said, if you have a solution to replace it easily, go for it I am accepting PRs :)
